### ISSUE TITLE
Able to view home page after clicking Reddit icon

### ISSUE THREAD

**Issue by ghost** [HZ757/reddit-liberation-extension#2]
Thanks for this extension, Henry! It's been really valuable for me. I did notice a bug, however. When I'm viewing a comment thread, I can click the Reddit icon in the upper left corner and I can view my home page. It is no longer blocked. At that point, I can also click on and view any subreddit on my home page (even ones that aren't blacklisted).

**Comment by HZ757** [comment]
Thanks for the feedback! I will check it out.

**Comment by HZ757** [comment]
Hey Jasmin, sorry for the long delay. I seem to have fixed the issue with the latest commit. Uploading it onto the play store, you should get the update soon once it's past the google review (within days or a week).

**Comment by ghost** [comment]
No worries at all. Thank you so much for looking into it!

**Comment by ghost** [comment]
Looks like the issue is resolved. Thanks again!
