### ISSUE TITLE
Add a LICENSE and contribution guidelines

### ISSUE THREAD

**Issue by ThoolooExpress** [HZ757/reddit-liberation-extension#3]
I like the idea of this extension, and would be interested in contributing some minor improvements, but I noticed that you haven't specified whether you're interested in outside contributions, or what license this code is released under.

If you are open to outside contributions, you should say so and specify a license. Most companies prohibit their employees from contributing to open-source projects that do not specify a license, even if their patching policies are generally very permissive.  I'd recommend the MIT license as a reasonable default for this sort of project, but https://choosealicense.com/ can help you if you'd like more control over how your project can be used and aren't familiar with the options available to you. Also see GitHub's docs:

- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

If you aren't open to contributions, that's fine too, but you should still consider specifying license terms, even if they are "all rights reserved," and clearly state that you aren't interested in contributions. This will both ensure that your rights are protected, and that there is no confusion in the future.

**Comment by HZ757** [comment]
Hi ThoolooExpress, 

Thanks for notifying me of this! I would be glad for you and the community to contribute to this. I will add the MIT license, so anybody will be free to go ahead and contribute.

**Comment by ThoolooExpress** [comment]
That's perfect, thanks!
